# Generated by Django 5.1.13 on 2025-10-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_prestamos_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='libros',
        ),
        migrations.AddField(
            model_name='cliente',
            name='libros_preferidos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libros_preferidos', to='biblioteca.libro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='libros_prestamos',
            field=models.ManyToManyField(related_name='libros_prestamo', through='biblioteca.Prestamo', to='biblioteca.libro'),
        ),
    ]
